[tox]
envlist = py38,py39,py310,py311,py312,py313
skipsdist=True

[gh-actions]
problem_matcher = False
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
install_command = {envpython} -m pip install -v {opts} {packages}
commands =
    {envpython} -m pip install -e . -v
    pytest --junitxml={toxinidir}/reports/test-{envname}.xml {posargs:--cov-report term}
    {envpython} -c "import os; os.path.exists('{toxworkdir}/coverage') or os.makedirs('{toxworkdir}/coverage')"
usedevelop = True
setenv =
    COVERAGE_FILE={toxworkdir}/coverage/.coverage.{envname}
passenv =
    FFMPEG_PATH
    FFPROBE_PATH
    PYTEST_ADDOPTS
deps =
    coverage
    pytest
    pytest-mock
    pytest-tornado
    pytest-cov
    thumbor
    pytest-asyncio
    !py313: thumbor-aws
    mirakuru
    moto[server]

[testenv:coverage-report]
skip_install = true
deps = coverage
setenv=COVERAGE_FILE=.coverage
changedir = {toxworkdir}/coverage
commands =
    coverage combine
    coverage report
    coverage xml -o {toxinidir}/coverage.xml

[testenv:codecov]
skip_install = true
deps = codecov
depends = coverage-report
passenv = CODECOV_TOKEN
changedir = {toxinidir}
commands =
    codecov --file {toxinidir}/coverage/coverage.xml {posargs}
