name: Auto-merge Dependabot

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  dependabot-automerge-github-actions:
    if: github.event_name != 'pull_request' || github.event.pull_request.user.login == 'dependabot[bot]'

    permissions:
      pull-requests: write
      contents: write
      issues: write
    uses: theatlantic/workflows/.github/workflows/dependabot-automerge.yml@main
    secrets:
      AUTOMERGE_TOKEN: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}
    with:
      allowed-ecosystems: 'github_actions'
      allowed-update-types: 'minor,patch,major'
      merge-method: 'squash'
      days-to-wait: 10
      security-fast-track: true
      approve-only: false
