name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python-version }}

    env:
      GIFSICLE_VER: 1.92

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ffmpeg
        run: |
          container=$(docker create mwader/static-ffmpeg:7.1.1)
          sudo docker cp $container:/ffmpeg /usr/bin/ffmpeg
          sudo docker cp $container:/ffprobe /usr/bin/ffprobe
          docker rm $container

      - name: Install gifsicle
        run: |
          curl -sLo - http://www.lcdf.org/gifsicle/gifsicle-1.92.tar.gz | \
              tar Czxf . -
          cd gifsicle-${{ env.GIFSICLE_VER }}
          ./configure --prefix=/usr
          sudo make install
          rm -rf gifsicle-${{ env.GIFSICLE_VER }}

      - name: Install gifski
        run: |
          cargo install gifski

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install tox
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install tox tox-gh-actions wheel

      - name: Run tests
        run: |
          tox -- -v

      - name: Upload junit xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports-${{ matrix.python-version }}
          path: reports/*.xml

      - name: Combine coverage
        run: tox -e coverage-report

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          name: ${{ github.workflow }}
          token: ${{ secrets.CODECOV_TOKEN }}

  report:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    name: "Report Test Results"
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: junit-reports-*
          merge-multiple: true

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ./*.xml
          report_individual_runs: true
          check_name: "Unit Test Results"

  success:
    needs: build
    runs-on: ubuntu-latest
    name: Test Successful
    steps:
      - name: Success
        run: echo Test Successful
